name: Deploy Fake
on:
    workflow_call:
jobs: 
    deploy-kubernetes:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ secrets.AMBIENTE_ENTREGA }}"
            - name: Curl Deploy no ambiente
              run: "curl -X POST https://webhook.site/feb6ce45-2fd9-47c0-bbee-34dca5268a62 -d '{ ambiente: ${{ secrets.AMBIENTE_ENTREGA }}}'"